### ISSUE TITLE
 The obs returned by the `step()` method length is not same as the observation space length, obs length: 95, space length: 4

### ISSUE THREAD

**Issue by dongdoodle** [inf581-pvz-anonymous/pvz_rl#2]
Running python game_render.py, we facing the Traceback

Traceback (most recent call last):
  File "game_render.py", line 145, in <module>
    env.play(agent)
  File "pvz_rl\agents\ddqn_agent.py", line 392, in play
    observation, reward, done, info = self.env.step(action)
  File "gym\wrappers\order_enforcing.py", line 37, in step
    return self.env.step(action)
  File "gym\wrappers\env_checker.py", line 37, in step
    return env_step_passive_checker(self.env, action)
  File "gym\utils\passive_env_checker.py", line 246, in env_step_passive_checker
    check_obs(obs, env.observation_space, "step")
  File "gym\utils\passive_env_checker.py", line 150, in check_obs
    assert len(obs) == len(
AssertionError: The obs returned by the `step()` method length is not same as the observation space length, obs length: 95, space length: 4

**Comment by ZXX-Andrew** [comment]
I met the same problem either, do you now have any idea on how to solve this? TAT

**Comment by ZXX-Andrew** [comment]
I solved this problem now. You can just change the version of gym to 0.12.5, then it will be all fine.
